name: Clear Notebook Outputs

on:
  push:
    branches:
      - '**'  # This will trigger the workflow on pushes to any branch

jobs:
  clear-outputs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to the latest version
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install Jupyter
      run: pip install nbformat

    - name: Clear outputs from Jupyter notebooks
      run: |
        find . -name "*.ipynb" -exec jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace {} \;

    - name: Commit cleared notebooks
      uses: stefanzweifel/git-auto-commit-action@v5  # Updated to the latest version
      with:
        commit_message: 'Automatically clear notebook outputs'
        file_pattern: '*.ipynb'
        branch: ${{ github.ref }}